# Generated by Django 4.0.4 on 2022-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
