# Generated by Django 4.0.4 on 2022-05-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_rename_image_image_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='title',
        ),
    ]
