# Generated by Django 4.0.4 on 2022-05-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_rename_name_category_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
